name: 🐞 Bug
description: File a bug report
title: "[Bug]: <YOUR TITLE HERE>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please [search](https://github.com/b-kennedy0/b-kennedy0.github.io/issues) to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing open and closed issues
        required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can I get in touch with you if I need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? / Describe the bug
      description: Also tell me, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: dropdown
    id: device
    attributes:
      label: What device are you seeing the problem on?
      multiple: true
      options:
        - PC
        - Laptop
        - Mobile Phone
        - Tablet
  - type: textarea
    attributes:
      label: Environment (if relevant)
      description: |
        examples:
          - **OS**: iOS
          - **Browser**: Chrome, Safari
          - **Version**: v20.1
      value: |
          - OS:
          - Browser:
          - Version:
      render: Markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give me more context about the issue you are encountering!

        Tip: You can attach images/screenshots or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
